### ISSUE TITLE
What is the achievement? + Code review

### ISSUE THREAD

**Issue by WebReflection** [Rich-Harris/dom-monster#2]
Once clarified that this benchmark was about performance and not style, what are you trying to achieve here?

Your code style looks more prolix for no concrete reason, it creates instances of Rows without any benefit, coupling nodes with objects which is as memory leaks prone as my closures, if these objects are never freed. You are using more RAM, and you constantly access properties so you do a lot of extra lookup.

This is a benchmark, not a code-style lesson, but since you apparently think it was ... and since you wasted time to write that down, here my review:
### Leaking globals

You use a closure, which is good, but [you leak globals regardless](https://github.com/Rich-Harris/dom-monster/blob/gh-pages/index.html#L37-L38).
Using capitalized variable names does not grant you automatically the privilege to leak globally.
### Why is there a TIMEOUT = 0 ?

You are using `requestAnimationFrame` [right here](https://github.com/Rich-Harris/dom-monster/blob/gh-pages/index.html#L30) ... in case you didn't know, that's DOM, not underscore or any other framework. Why are you leaking a TIMEOUT variable to use a misleading `setTimeout(fn, 0)` at the end of the function?
Did you know that intervals never goes under 4ms in recent browsers, and used to never go under 10 before? What kind of good practice is a globally leaking TIMER variable to use a timer instead of `requestAnimationFrame` ?
### Why is there a ROWS = 100 ?

You were planning to use a static length or something? That's completely unused, you forgot to lint your code. Any linter would have found that unused variable.
### IFI => "use strict"

Since you put an IFI in place, where is the guarding `"use strict"` that grants we are not leaking globals in that closure too? https://github.com/Rich-Harris/dom-monster/blob/gh-pages/index.html#L40
### DRY

You are repeating countlessly the same operation over and over. I hope you don't consider this a good coding style or pattern. [As shown in my code](https://github.com/WebReflection/dbmonster/blob/master/index.html#L36-L41)

``` js
  function append(where, what) {
    return where.appendChild(
      (where.ownerDocument || document).createElement(what)
    );
  }
```

This would minify much better and make you write much less code ... it's too late, you already wrote that code but I would not encourage such style. There is a closure? Use it for what its good at.
### Hoisted multiple variable declarations

It's usually considered a bad practice to declare variables down the road, but if you do that because you have a `for` loop, then do it in a better way.

``` js
// yak!
var cell;
for ( var i = 0; i < 5; i += 1 ) {


// ... oh, much better
for ( var cell, i = 0; i < 5; i += 1 ) {
```

You have one place where you need those two variables: inside that for loop.
( there's no problem with leaking globals, there is only if you forget use strict and a linter before deploying ... but then you have a bigger problem than just a leak )

Same stuff [repeated here](https://github.com/Rich-Harris/dom-monster/blob/gh-pages/index.html#L90-L93)
### missing `key` attribute and a bug

You are not setting the row `key` attribute as the original benchmark does.
This `if` statement [is always true](https://github.com/Rich-Harris/dom-monster/blob/gh-pages/index.html#L97)
I guess that's the result of premature optimizations pattern you used.
### As Summary

I cared only about the benchmark in my code, and I wrote that in minutes.

I've explained few used patterns, and I've created the smaller memory footprint needed on JS land for that benchmark.

I've clearly stated I didn't even care about the style, only about quickly bringing the benchmark in DOM land so ...

If you want to make it a life lesson about coding, there's a lot to improve here too, and so many unnecessary extra objects I don't know where to start dropping stuff.

You are coding a benchmark, the used RAM and the amount of code for startup should be more important if you want to shine in this competition.

And this is also a problem I've implicitly discussed in my blog post: developers tend to over engineer even the most simple task.

You created a class called `Row` to actually wrap a `tr` which is already a row. Do you feel better now that you have an `update` method through a wrapper, instead of an `update` function?

Good for you, but please don't tell the world that's how everyone should code, specially how everyone should code a benchmark.

Best Regards

**Comment by Rich-Harris** [comment]
The achievement is a faster benchmark. I'm basically agreeing with you! If frameworks and libraries are going to make bold claims, you're totally right that they should hold themselves to the highest possible standard.

I already said on the [README](https://github.com/Rich-Harris/dom-monster/blob/gh-pages/README.md#something-like-this-presumably) that this is _really bad code_. It's designed to be fast, not pretty. (In fact that's kind of my whole point - without a suitable abstraction giving you a decent higher-level vocabulary with which to write a program, the code quickly turns ugly.)

Having said that...

> You are using more RAM

About 300kb, yeah. The beauty of prototypal inheritance is that I could add a bunch of extra methods to my rows (`hide()`, `highlight()`, whatever) and the memory footprint would barely budge. I think that's harder to do with persistent closures.

> and you constantly access properties so you do a lot of extra lookup.

That's basically the reason that this version is faster - it only touches the DOM when data has changed. If we combined our approaches and used closures, but checked whether data had changed each time, we'd probably find we got the best of both worlds.

Leaking globals, ROWS, TIMEOUT etc... yeah this is a fork of [Jeremy Ashkenas' version](https://github.com/jashkenas/dbmonster), which is adapted from somewhere else... maybe the original intention was that you could change values via the console. Whatever. I just copied and pasted that part. As for the `setTimeout`, all the other implementations use `setTimeout` and I wanted to be consistent with them. Having said that, I swapped in `rAF` and the framerate dropped. ¯\ _ (ツ) _/¯ 

The rest of your comments, well, sure. We could go back and forth ad nauseam, but let's not. Like you, I was just cobbling together some code for the purposes of the benchmark, and like I already said several times over, this is the whole reason that abstractions are so valuable - you get nice concise code without having to worry about micro-optimisations, or other developers having different opinions about patterns.

Can I be change the subject for a moment? When you write, you often come across in a really hostile way. Maybe that's not your intention - it's easy to misinterpret stuff online - but it's what the reader sees. There's no need for it! No-one is attacking you personally (I'm certainly not - I'm just interested in furthering the discussion that you started, and this benchmark is an extension of that), and...

> if you want to shine in this competition

...it's not a competition, it's a collaboration! We're all on the same team at the end of the day - we all want the web to be the best platform possible. <3

**Comment by WebReflection** [comment]
You are not setting the key attribute and once you have that, i want to see it's faster than mine. If we were on the same team, you wouldn't have duplicated my effort, you would have discussed and sent a PR there. I don't see the point of having extra wasted 300KB and a prototype for a well defined task/benchmark that doesn't need to be maintained, it needs to show it's fast.

-----Original Message-----

**Comment by WebReflection** [comment]
Moreover, now that I think about it ... your main complains where about my code style.

Instead of sending a PR or discussing in the repository I've linked in my post:
https://github.com/WebReflection/dbmonster

You create a new one with a "_warning, this code is bad_" in the REAME ?

If this is not attacking or trolling, can you explain to me what are you trying to achieve?

Do you really want to teach me what are prototype benefits after 15 years I use them?

Again: what are you trying to achieve with this project?

**Comment by Rich-Harris** [comment]
Look, Andrea, I'm bored of this discussion.You're taking everything in bad faith, twisting words, and failing to actually read my comments.

My 'main complaint' was never about your code style - I merely mentioned in passing that your code was confusing (a sentiment echoed by others, e.g. on Reddit), not to attack you, but to point out that that's the cost of not using abstractions.

> Do you really want to teach me what are prototype benefits after 15 years I use them?

Boasting about your experience is the worst way to win an argument. I was defending my use of them, that's all, after you attacked it.

Again, what I hoped to achieve with this repo is to have the fastest possible DOM-only benchmark against which tools can test themselves, **because I agree with you that that's important**.

I won't be engaging with you any more on this discussion, because I have work to do and this is taking too much time. Thank you for taking the time to write the original article, and for presenting your research, but PLEASE work on your communication style. Have a nice day.

**Comment by WebReflection** [comment]
[You already had it](https://github.com/WebReflection/dbmonster/blob/master/index.html), it misses just a couple of (meh) checks to avoid textContent or className calls.

This project wasn't needed, it smells like trolling since the README that blames me of some FUD, and it's already 300KB out of needed RAM chart.

But don't worry, I won't engage further neither.
